# Provision masters and slave servers topology
---
- name: Provision a clustered master-slave topology messaging broker
  hosts: cluster
  vars:
    - amq_broker_start_server: false
  vars_files:
    - group_vars/variables.yml
  roles:
    - roles/cluster

- name: Fine-tune cluster on master hosts
  hosts: master
  vars:
    - amq_broker_start_server: false
    - host_type: master
  vars_files:
    - group_vars/variables.yml
  roles:
    - roles/ha-replication

- name: Fine-tune cluster on slave hosts
  hosts: slave
  vars:
    - amq_broker_start_server: false
    - host_type: slave
  vars_files:
    - group_vars/variables.yml
  roles:
    - roles/ha-replication
#
# # Actual test steps
# - name: Start all master/slave brokers
#   hosts: cluster
#   tasks:
#   - name: Start brokers
#     vars:
#       amq_broker_start_server: true
#       amq_broker_service_start: true
#       amq_broker_instance_dir: entmqbr-469
#     include_role:
#       name: amq-broker
#       tasks_from: service_start_amq_broker_instance.yml
#
# - name: "Isolate slave on slave3 node"
#   hosts: r63
#   tasks:
#   - pause:
#       prompt: "Check cluster status. Hit key to continue with isolating slave on {{ ansible_hostname }}"
#   - name: Isolate {{ ansible_hostname }} by REJECT incoming/outgoing tcp port 61616
#     vars:
#       iptables_packet_policy: REJECT
#       iptables_protocol: tcp
#       iptables_state: present  # {present, absent}
#       item: 61616
#     include_role:
#       name: amq-broker
#       tasks_from: configure_iptables_amq_broker.yml
