# Provision masters and slave servers topology
---
- name: Provision a clustered master-slave topology messaging broker
  hosts: cluster
  vars:
    - amq_broker_start_server: false
  vars_files:
    - group_vars/variables.yml
  roles:
    - roles/cluster

- name: Fine-tune cluster on master hosts
  hosts: master
  vars:
    - amq_broker_start_server: false
    - host_type: master
  vars_files:
    - group_vars/variables.yml
  roles:
    - roles/ha-replication

- name: Fine-tune cluster on slave hosts
  hosts: slave
  vars:
    - amq_broker_start_server: false
    - host_type: slave
  vars_files:
    - group_vars/variables.yml
  roles:
    - roles/ha-replication
